// <auto-generated />
using CSC237_JMarshall_ProgrammingChallenge1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CSC237_JMarshall_ProgrammingChallenge1.Migrations
{
    [DbContext(typeof(ContactContext))]
    [Migration("20200215190704_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CSC237_JMarshall_ProgrammingChallenge1.Models.Contact", b =>
                {
                    b.Property<int>("contactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("contactID");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            contactID = 1,
                            firstName = "James",
                            lastName = "marshall",
                            phone = "720-965-1983"
                        },
                        new
                        {
                            contactID = 2,
                            firstName = "Philip",
                            lastName = "marshall",
                            phone = "720-965-2248"
                        },
                        new
                        {
                            contactID = 3,
                            firstName = "Sarah",
                            lastName = "marshall",
                            phone = "720-965-1111"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
